# Generated by Django 6.0.5 on 2026-06-04 17:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sessionanswer',
            index=models.Index(fields=['session', 'question'], name='progress_se_session_c6e79f_idx'),
        ),
        migrations.AddIndex(
            model_name='userquestionprogress',
            index=models.Index(fields=['user', 'due_date'], name='progress_us_user_id_c77c0c_idx'),
        ),
        migrations.AddIndex(
            model_name='userquestionprogress',
            index=models.Index(fields=['user', 'card_state'], name='progress_us_user_id_a5372e_idx'),
        ),
    ]
